import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
let source=readFileSync('app/account-roster.ts','utf8').replace("import 'server-only';",'').replace("import snapshotData from './account-roster-data.json';","const snapshotData={};").replaceAll("'./account-ledger'",`'${process.cwd()}/app/account-ledger.ts'`);
const compiled=execFileSync('node_modules/.bin/esbuild',['--bundle','--format=esm','--platform=node','--target=node20','--loader=ts'],{input:source});
const {accountRosterFallback,mergeAccountRoster}=await import(`data:text/javascript;base64,${compiled.toString('base64')}`);
const snapshot={tenantId:'j-packaging',invoiceMonth:'2026-10',statementMonth:'2026-09',generatedAt:'2026-10-06T04:00:00Z',sourceReference:'private-source',rows:[{id:'one',entity:'Entity',market:'MY',project:'Project',termsVersion:'NEW',mappingStatus:'candidate',mappingReason:'Needs confirmation',sourceRow:8,candidates:[{mappingId:'m',username:'store-user',storeId:null,storeName:'Store'}]}]};
test('snapshot only visible to intended dataset tenant and exact billing cycle',()=>{assert.equal(accountRosterFallback('other','2026-10','2026-10-06',new Map(),snapshot),null);assert.equal(accountRosterFallback('j-packaging','2026-11','2026-10-06',new Map(),snapshot),null);});
test('historical binding remains candidate, never finance or live sync; internal provenance stays server-side',()=>{const result=accountRosterFallback('j-packaging','2026-10','2026-10-06',new Map(),snapshot);assert.equal(result.stores[0].storeId,null);assert.equal(result.stores[0].mappingStatus,'candidate');assert.equal(result.stores[0].status,'pending_mapping');assert.equal(result.stores[0].expectedNetFee,null);assert.equal(result.summaries[0].billed,null);assert.equal(result.summaries[0].pendingStores,1);assert.equal(result.updatedAt,null);assert.equal(result.rosterUpdatedAt,snapshot.generatedAt);assert.doesNotMatch(JSON.stringify(result),/private-source|sourceRow/);});
test('one-to-many and shared candidates stay separate and unresolved',()=>{const fixture=structuredClone(snapshot);fixture.rows[0].mappingStatus='ambiguous';fixture.rows[0].candidates.push({mappingId:'m2',username:'second-store',storeId:null,storeName:'Second'});const row=accountRosterFallback('j-packaging','2026-10','2026-10-06',new Map(),fixture).stores[0];assert.equal(row.storeId,null);assert.equal(row.candidates.length,2);assert.equal(row.mappingStatus,'ambiguous');});
test('resolved binding must exist within tenant store roster; still no monetary source',()=>{const fixture=structuredClone(snapshot);fixture.rows[0].mappingStatus='resolved';fixture.rows[0].candidates[0].storeId='store';assert.equal(accountRosterFallback('j-packaging','2026-10','2026-10-06',new Map(),fixture).stores[0].mappingStatus,'missing');const row=accountRosterFallback('j-packaging','2026-10','2026-10-06',new Map([['store','Tenant Store']]),fixture).stores[0];assert.equal(row.storeName,'Tenant Store');assert.equal(row.status,'pending_source');assert.equal(row.collected,null);});

test('audited source contains 58 tenant-scoped rows without leaking provenance or inferring values',()=>{const real=JSON.parse(readFileSync('app/account-roster-data.json','utf8'));const result=accountRosterFallback('j-packaging','2026-10','2026-10-06',new Map(),real);assert.equal(result.stores.length,58);assert.equal(result.stores.filter(r=>r.market==='MY').length,45);assert.equal(result.stores.filter(r=>r.market==='SG').length,13);assert.ok(result.stores.every(r=>r.expectedNetFee===null&&r.storeId===null));assert.doesNotMatch(JSON.stringify(result),/sourceRow|sourceTab|projectId|internalExternal/);});
test('partial ledger preserves remaining roster via stable key only, cash never duplicated',()=>{const roster=accountRosterFallback('j-packaging','2026-10','2026-10-06',new Map(),snapshot);const base=structuredClone(roster);base.stores=[{...roster.stores[0],id:'term-id',rosterKey:'one',expectedNetFee:'100.00',status:'assessed'}];base.summaries[0].monthCollected='42.00';assert.equal(mergeAccountRoster(base,roster).stores.length,1);assert.equal(base.summaries[0].monthCollected,'42.00');base.stores[0].rosterKey='unrelated';assert.equal(mergeAccountRoster(base,roster).stores.length,2);assert.equal(base.summaries[0].pendingStores,1);assert.equal(base.summaries[0].monthCollected,'42.00');});
