import {test} from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const compiled=execFileSync('node_modules/.bin/esbuild',['app/account-ledger.ts','--bundle','--format=esm','--platform=node','--target=node20']);
const {buildAccount,cents,decimal,malaysiaDate,emptyAccount}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const updated_at='2026-10-06T00:00:00Z';
function ledger() { return {cycles:[{id:'c',statement_month:'2026-09-01',invoice_month:'2026-10-01',service_period_start:null,service_period_end:null,updated_at}],terms:[{id:'t',roster_project:'Project',store_id:'store',currency:'MYR',confirmed:true,effective_from:'2026-10-01',effective_to:null,updated_at}],assessments:[{id:'a',cycle_id:'c',term_id:'t',expected_net_fee:'100.10',status:'verified',updated_at}],invoices:[{id:'i',assessment_id:'a',gross_amount:'108.11',credit_amount:'0.00',status:'issued',updated_at}],receipts:[],allocations:[],storeNames:new Map([['store','Store']])}; }
function receipt(id,amount,date='2026-10-05',kind='receipt',currency='MYR') { return {id,amount,collection_date:date,kind,currency,status:'verified',updated_at}; }
test('exact decimals exceed JavaScript safe integer without loss',()=>assert.equal(decimal(cents('9999999999999999.99')+cents('0.01')),'10000000000000000.00'));
test('Malaysia day boundary and empty ledger preserve unknown totals',()=>{assert.equal(malaysiaDate(new Date('2026-10-05T16:01:00Z')),'2026-10-06');const empty=emptyAccount('2026-10','2026-10-06');assert.equal(empty.statementMonth,'2026-09');assert.equal(empty.summaries[0].collected,null);});
test('partial receipts reduce outstanding without becoming assessments',()=>{const l=ledger();l.receipts=[receipt('r','30.00')];l.allocations=[{receipt_id:'r',invoice_id:'i',amount:'30.00',updated_at}];const s=buildAccount(l,'2026-10','2026-10-06').summaries[0];assert.equal(s.billed,'108.11');assert.equal(s.collected,'30.00');assert.equal(s.outstanding,'78.11');assert.equal(s.todayCollected,null);assert.equal(s.monthCollected,'30.00');});
test('invoice-cycle collections differ from collection-month cash, refunds and unallocated cash included',()=>{const l=ledger();l.receipts=[receipt('old','50.00','2026-09-30'),receipt('refund','10.00','2026-10-06','refund'),receipt('new','5.00','2026-10-06')];l.allocations=[{receipt_id:'old',invoice_id:'i',amount:'50.00',updated_at},{receipt_id:'refund',invoice_id:'i',amount:'10.00',updated_at}];const s=buildAccount(l,'2026-10','2026-10-06').summaries[0];assert.equal(s.collected,'40.00');assert.equal(s.todayCollected,'-5.00');assert.equal(s.monthCollected,'-5.00');});
test('one overpaid invoice does not conceal another unpaid invoice',()=>{const l=ledger();l.invoices.push({...l.invoices[0],id:'i2'});l.receipts=[receipt('r','150.00')];l.allocations=[{receipt_id:'r',invoice_id:'i',amount:'150.00',updated_at}];const s=buildAccount(l,'2026-10','2026-10-06').summaries[0];assert.equal(s.outstanding,'108.11');assert.equal(s.overpaid,'41.89');});
test('unconfirmed mapping and terms never publish inferred expected fees',()=>{const l=ledger();l.terms[0].confirmed=false;const result=buildAccount(l,'2026-10','2026-10-06');assert.equal(result.stores[0].expectedNetFee,null);assert.equal(result.summaries[0].expectedNetFee,null);assert.equal(result.stores[0].status,'pending_terms');});
test('cross-currency and receipt over-allocation fail reconciliation',()=>{const l=ledger();l.receipts=[receipt('r','30.00','2026-10-06','receipt','SGD')];l.allocations=[{receipt_id:'r',invoice_id:'i',amount:'30.00',updated_at}];assert.throws(()=>buildAccount(l,'2026-10','2026-10-06'),/currency/);l.receipts[0].currency='MYR';l.allocations[0].amount='31.00';assert.throws(()=>buildAccount(l,'2026-10','2026-10-06'),/over-allocated/);});
test('void and future receipts do not affect cash or receivables',()=>{const l=ledger();l.receipts=[{...receipt('v','50.00'),status:'void'},receipt('f','50.00','2026-10-07')];l.allocations=l.receipts.map(r=>({receipt_id:r.id,invoice_id:'i',amount:'50.00',updated_at}));const s=buildAccount(l,'2026-10','2026-10-06').summaries[0];assert.equal(s.collected,'0.00');assert.equal(s.outstanding,'108.11');assert.equal(s.monthCollected,null);});
test('evidenced zero fee remains zero; absent statements stay unknown',()=>{const l=ledger();l.assessments[0].expected_net_fee='0.00';assert.equal(buildAccount(l,'2026-10','2026-10-06').summaries[0].expectedNetFee,'0.00');l.assessments=[];l.invoices=[];const s=buildAccount(l,'2026-10','2026-10-06').summaries[0];assert.equal(s.expectedNetFee,null);assert.equal(s.billed,null);});
test('collection-month cash survives a different invoice-month filter and currencies remain separate',()=>{const l=ledger();l.receipts=[receipt('sg','10.00','2026-10-06','receipt','SGD')];const s=buildAccount(l,'2026-11','2026-10-06').summaries;assert.equal(s[0].monthCollected,null);assert.equal(s[1].monthCollected,'10.00');assert.equal(s[1].billed,null);});
