import {test} from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const compiled=execFileSync('node_modules/.bin/esbuild',['app/account-settings-model.ts','--bundle','--format=esm','--platform=node','--target=node20']);
const {validateFeeRule,applyAccountSettings}=await import(`data:text/javascript;base64,${compiled.toString('base64')}`);
const zero={currency:'MYR',expectedNetFee:null,billed:null,collected:null,outstanding:null,overpaid:null,todayCollected:null,monthCollected:null,pendingStores:0};
function account(month){return {invoiceMonth:month,statementMonth:'2026-09',today:'2026-10-07',timezone:'Asia/Kuala_Lumpur',status:'ready',updatedAt:null,summaries:[{...zero}],stores:[]};}
const rule={type:'fixed',currency:'MYR',basis:'fixed_monthly',fixedAmount:'100.00'};
function version(v,month,action,storeId,feeRule){return {id:`v${v}`,roster_key:'roster-2026-10-my-2',roster_project:'Project',legal_entity:'Entity',currency:'MYR',change_action:action,version:String(v),effective_month:`${month}-01`,store_id:storeId,fee_rule:feeRule,created_at:'2026-10-07T00:00:00Z'};}
test('future configured unit appears in November preserving market, but not October or other 57 unconfirmed units',()=>{const settings=[version(1,'2026-11','mapping','store',null)];assert.equal(applyAccountSettings(account('2026-10'),settings,new Map([['store','Store']])).stores.length,0);const row=applyAccountSettings(account('2026-11'),settings,new Map([['store','Store']])).stores[0];assert.equal(row.storeId,'store');assert.equal(row.market,'MY');assert.equal(row.expectedNetFee,null);assert.equal(row.calculatedFee,null);});
test('future mapping then current fee persists both timelines independently',()=>{const settings=[version(1,'2026-11','mapping','store',null),version(2,'2026-10','fee_rule',null,rule)];const october=applyAccountSettings(account('2026-10'),settings,new Map([['store','Store']])).stores[0];assert.equal(october.storeId,null);assert.equal(october.rateRule.fixedAmount,'100.00');const november=applyAccountSettings(account('2026-11'),settings,new Map([['store','Store']])).stores[0];assert.equal(november.storeId,'store');assert.equal(november.rateRule.fixedAmount,'100.00');assert.equal(november.mappingEffectiveMonth,'2026-11');assert.equal(november.rateEffectiveMonth,'2026-10');assert.equal(november.rateHistory.length,1);});
test('future fee then current mapping persists reverse timeline and leaves old month fee pending',()=>{const settings=[version(1,'2026-11','fee_rule',null,rule),version(2,'2026-10','mapping','store',null)];const october=applyAccountSettings(account('2026-10'),settings,new Map([['store','Store']])).stores[0];assert.equal(october.storeId,'store');assert.equal(october.rateRule,null);const november=applyAccountSettings(account('2026-11'),settings,new Map([['store','Store']])).stores[0];assert.equal(november.storeId,'store');assert.equal(november.rateRule.fixedAmount,'100.00');assert.equal(november.latestSettingsVersion,'2');});
test('later versions do not change earlier month rule or erase receipts',()=>{const data=account('2026-10');data.summaries[0].todayCollected='25.00';const row=applyAccountSettings(data,[version(1,'2026-10','fee_rule',null,rule),version(2,'2026-11','fee_rule',null,{...rule,fixedAmount:'200.00'})],new Map()).stores[0];assert.equal(row.rateRule.fixedAmount,'100.00');assert.equal(data.summaries[0].todayCollected,'25.00');});
test('fixed values are exact but not recorded as billed/cash income',()=>{const checked=validateFeeRule({...rule,fixedAmount:'9999999999999999.99'},'MYR');assert.equal(checked.fixedAmount,'9999999999999999.99');const row=applyAccountSettings(account('2026-10'),[version(1,'2026-10','fee_rule',null,checked)],new Map()).stores[0];assert.equal(row.billed,null);assert.equal(row.calculatedFee,null);});
test('missing decimal/type/custom basis label rejected, zero is valid',()=>{assert.equal(validateFeeRule({...rule,fixedAmount:'0'},'MYR').fixedAmount,'0.00');for(const input of [{...rule,fixedAmount:null},{...rule,type:undefined},{type:'percent',currency:'MYR',basis:'custom',percent:'3'},{type:'percent',currency:'MYR',basis:'net_gmv',percent:null}])assert.throws(()=>validateFeeRule(input,'MYR'));});
test('tier bounds, currency and min/cap validation',()=>{assert.throws(()=>validateFeeRule({type:'tiers',currency:'MYR',basis:'net_gmv',tiers:[{from:'0',percent:'3'},{from:'0',percent:'2'}]},'MYR'));assert.throws(()=>validateFeeRule({...rule,currency:'SGD'},'MYR'));assert.throws(()=>validateFeeRule({...rule,minimum:'100',cap:'50'},'MYR'));});
