import {test} from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {readFileSync} from 'node:fs';
let source=readFileSync('app/account-settings.ts','utf8').replace("import 'server-only';",'').replace("import roster from './account-roster-data.json';",`const roster={tenantId:'j-packaging',rows:[{id:'roster-2026-10-my-2',project:'Project',entity:'Entity',market:'MY'}]};`)
.replace(/import \{ getChatGPTUser \}[^;]+;/,'const getChatGPTUser=async()=>globalThis.__actor;').replace(/import \{ supabaseRest \}[^;]+;/,'async function supabaseRest<T>(path:string,init?:RequestInit):Promise<T>{return globalThis.__rest(path,init);}')
.replaceAll("'./live-calendar-model'",`'${process.cwd()}/app/live-calendar-model.ts'`).replaceAll("'./account-ledger'",`'${process.cwd()}/app/account-ledger.ts'`).replaceAll("'./account-settings-model'",`'${process.cwd()}/app/account-settings-model.ts'`);
const compiled=execFileSync('node_modules/.bin/esbuild',['--bundle','--format=esm','--platform=node','--target=node20','--loader=ts'],{input:source});
const {saveAccountSetting}=await import(`data:text/javascript;base64,${compiled.toString('base64')}`);
const body={rosterKey:'roster-2026-10-my-2',storeId:'shopee-supu',effectiveMonth:'2099-10',expectedVersion:'0',requestId:'10000000-0000-4000-8000-000000000001'};
function request(data=body,origin='https://example.test'){return new Request('https://example.test/api/admin/account/mapping',{method:'PUT',headers:{'origin':origin,'content-type':'application/json'},body:JSON.stringify(data)});}
let paths=[],payload;
function setup({role='superadmin',active=true,tenant='j-packaging',exists=true,error=''}={}){paths=[];payload=null;globalThis.__actor={email:'SERVER-admin@example.test'};globalThis.__rest=async(path,init)=>{paths.push(path);if(path.startsWith('customer_users?'))return [{tenant_id:tenant,active,role}];if(path.startsWith('tenants?'))return [{active:true}];if(path.startsWith('stores?')){assert.match(path,/tenant_id=eq.j-packaging/);return exists?[{id:'shopee-supu'}]:[];}if(path.startsWith('rpc/')){payload=JSON.parse(init.body);if(error)throw new Error(error);return {version:'1'};}throw new Error('Unexpected read');};}
test('unauthenticated, inactive and non-SuperAdmin denied without writes',async()=>{setup();globalThis.__actor=null;assert.equal((await saveAccountSetting(request(),'mapping')).status,401);for(const opts of [{active:false},{role:'manager'},{role:'customer'},{tenant:'other-tenant'}]){setup(opts);assert.equal((await saveAccountSetting(request(),'mapping')).status,403);assert.ok(paths.every(p=>!p.startsWith('rpc/')));}});
test('cross-origin, unknown roster key and alias/foreign store ID rejected',async()=>{setup();assert.equal((await saveAccountSetting(request(body,'https://evil.test'),'mapping')).status,403);assert.equal((await saveAccountSetting(request({...body,rosterKey:'other-unit'}),'mapping')).status,400);assert.equal((await saveAccountSetting(request({...body,storeId:'shopee-skindae-sg-by-ctg4u'}),'mapping')).status,400);setup({exists:false});assert.equal((await saveAccountSetting(request(),'mapping')).status,400);assert.equal(payload,null);});
test('mapping writes trusted tenant/actor and audited unit, ignores caller spoofing',async()=>{setup();const response=await saveAccountSetting(request({...body,tenantId:'evil-tenant',actor:'spoof@example.test'}),'mapping');assert.equal(response.status,200);assert.equal(payload.p_tenant,'j-packaging');assert.equal(payload.p_actor,'server-admin@example.test');assert.equal(payload.p_roster_project,'Project');assert.equal(payload.p_store_id,'shopee-supu');assert.equal(payload.p_rule,null);assert.equal(payload.p_expected_version,'0');assert.equal(payload.p_request_id,body.requestId);});
test('fee rule validation preserves exact configured money, without ledger writes',async()=>{setup();const response=await saveAccountSetting(request({...body,rule:{type:'fixed',currency:'MYR',basis:'fixed_monthly',fixedAmount:'9999999999999999.99'}}),'fee_rule');assert.equal(response.status,200);assert.equal(payload.p_rule.fixedAmount,'9999999999999999.99');assert.equal(payload.p_store_id,null);assert.ok(paths.every(p=>!p.startsWith('account_invoices')&&!p.startsWith('account_receipts')));});
test('invalid currency, custom basis, expectedVersion and requestId rejected before RPC',async()=>{for(const value of [{...body,expectedVersion:0},{...body,requestId:'invalid'},{...body,rule:{type:'percent',currency:'MYR',basis:'custom',percent:'3'}},{...body,rule:{type:'fixed',currency:'SGD',basis:'fixed_monthly',fixedAmount:'100'}}]){setup();assert.equal((await saveAccountSetting(request(value),'fee_rule')).status,400);assert.equal(payload,null);}});
test('optimistic concurrency conflict distinct from not-configured backend',async()=>{setup({error:'ACCOUNT_VERSION_CONFLICT'});assert.equal((await saveAccountSetting(request(),'mapping')).status,409);setup({error:'ACCOUNT_REQUEST_CONFLICT'});assert.equal((await saveAccountSetting(request(),'mapping')).status,409);setup({error:'Supabase REST 404: {"code":"PGRST202"}'});const response=await saveAccountSetting(request(),'mapping');assert.equal(response.status,503);assert.match((await response.json()).error,/not configured/);});
