export type ProjectContact = { project: string; href: string };
const contact = (project: string, code: string): ProjectContact[] => [{ project, href:`https://chat.whatsapp.com/${code}` }];
const links: Record<string, ProjectContact[]> = {
  "AgePros By Swissmed":contact("AgePros By Swissmed","KXUrrJ8UWCn1Nki0MALMp5"), "Berlanco Beauty Official":contact("Berlanco Beauty Official","LTwpmVQGwzLItf0AQUrT1c"), "Beyoute Official Store":contact("Beyoute Official Store","ERB3KAfzkAeAKk0DuUKFfq"), "BioTech by Swissmed":contact("BioTech by Swissmed","JyFKBuh7bCaHdYXyzJKe19"),
  "Bonlife Official Store":contact("Bonlife Official Store","HorBuFpSnzV6CW5M2Ifz4w"), "CTG4u Malaysia":contact("CTG4u Malaysia","EXYQzbQLDGTH421x3fLXbC"), "Daionica Official Store":contact("Daionica Official Store","H4BsgJWQ7IO2eP0iwyjCZd"), "Dancoly Paris HQ":contact("Dancoly Paris HQ","Ewxa9hCjO0V0G05nLuonrw"),
  "Dr Smile Whitening by CTG4u":contact("Dr Smile Whitening by CTG4u","Et2187yHmh17JXVYQewqEL"), "Funffy by CTG4u":contact("Funffy by CTG4u","FPrHVc3cxTu8kthKeHrZxi"), "GoHerb Official Store":contact("GoHerb Official Store","HiofSH0UtQE4FUmKRhmIvI"), "Hair Factory Official":contact("Hair Factory Official","ILGsQQ9RrlBJdohzGN3dY2"),
  "iLady Haircare by CTG4u":contact("iLady Haircare by CTG4u","KGltZE77PAMJoMUl5N5Hdw"), "J Packaging":contact("J Packaging","Hr1R1M4oYui001c5YWERL1"), "Jeeroul by CTG4u":contact("Jeeroul by CTG4u","CANclPKblafDxpTog0CieK"), "Jen Mommy Essential Oil":contact("Jen Mommy Essential Oil","FI5pia7MRXO9ah87inveIc"),
  "Jourish Natural Wellness":contact("Jourish Natural Wellness","IEwYJrSel6o9mdqKknhVOl"), "Kata Skincare Malaysia":contact("Kata Skincare Malaysia","HptR622IByo4Ed9I6BGMFK"), "LivAct Official Store":contact("LivAct Official Store","KprUX4VpsoVCttHiVJoTBD"), "M+ SkinPro by CTG4u":contact("M+ SkinPro by CTG4u","E4i89zdQFdl3WuOZwVQj7N"),
  "Master Nerv Official Store":contact("Master Nerv Official Store","HF6D8uRYwGW37rTJ3wOYi6"), "MCS Skincare by CTG4u":contact("MCS Skincare by CTG4u","IGgjhTAHzRC5StuyxuPwDf"), "MFormula Official":contact("MFormula Official","HqkTSWbaAk97z3PdVdlWZZ"), "Mizino Official Store":contact("Mizino Mix Enzyme","KpEW6FONvcwF9r5XNSsJlN"),
  "Mizino Premium":[{project:"Mizino Placenta",href:"https://chat.whatsapp.com/GSzJui32SspCu3DU2n1bfX"},{project:"Mizino SlimPro",href:"https://chat.whatsapp.com/J0xSovCWaEGJNwjJfTnRrZ"}], "Moesie Malaysia":contact("Moesie Malaysia","F2wA9a0u1q6BWD5oqpaX4S"),
  "Naturelish Bugucare by CTG4u":contact("Naturelish Bugucare by CTG4u","JWzTCu5c3iR4UP0EeCmLYP"), "Naturelish Eco Plus by CTG4u":contact("Naturelish Eco Plus by CTG4u","BSypRrkb9ikBKANXwCqZDV"), "Naturelish Isokae by CTG4u":contact("Naturelish Isokae by CTG4u","Jvp3FRC506HLvJlC5hyi3n"), "NatureLish Recovit by CTG4u":contact("NatureLish Recovit by CTG4u","L0zq1oEjP6I4CBMMxTkB5w"),
  "Naturelish Uro360 by CTG4u":contact("Naturelish Uro360 by CTG4u","I6Tiguhm2aPExbTXxFQein"), "NINOKO Official Store":contact("NINOKO Official Store","GM5GaV0ex28DimGtIPJ5IQ"), "NomoQ by CTG4u":contact("NomoQ by CTG4u","J0JMAI5s99GBITVU1OPzCJ"), "PAW PAWs Official":contact("PAW PAWs Official","BeUmU0FbXI601ZWEllM7Dd"),
  "Petavit Official Store":contact("Petavit Official Store","K4c5Br5iR9UDsfw2naw8Lh"), "Scale Gem Collagen by CTG4u":contact("Scale Gem Collagen by CTG4u","IIBmolMzNIqGlnVxMGH08m"), "Scale Story Official Store":contact("Scale Story Official Store","He7fIN4nxTsJvij81UJhHT"), "SkinDae MY by CTG4u":contact("SkinDae MY by CTG4u","Ck3iphtGtTG6DKeujTKyVN"),
  "True Golden Care by Naturelish":contact("True Golden Care by Naturelish","KkNyXTzuo8JCpaF2R0gWdV"), "White Skin Care":contact("White Skin Care","H0kZ5ccbG0hGiHux4uZCjz"), "Yuan Chuan Tang Herbal by CTG4u":contact("Yuan Chuan Tang Herbal by CTG4u","JGCPbz5MFFqG19WRL85n75"), "Zeero Skincare Official":contact("Zeero Skincare Official","E9deP3IYGC95uf8hBVXc4N"),
};
const aliases: Record<string,string> = {
  "Berlanco SG":"Berlanco Beauty Official", "Beyoute Singapore":"Beyoute Official Store", "Bonlife SG":"Bonlife Official Store", "Bugucare by Naturelish":"Naturelish Bugucare by CTG4u", "CTG4U Malaysia":"CTG4u Malaysia", "Dr Smile Whitening SG by CTG4u.sg":"Dr Smile Whitening by CTG4u", "Eco Plus by Naturelish":"Naturelish Eco Plus by CTG4u", "Go Herb Singapore":"GoHerb Official Store",
  "iLady Haircare SG by CTG4u":"iLady Haircare by CTG4u", "ILady SG":"iLady Haircare by CTG4u", "KATA Care Malaysia":"Kata Skincare Malaysia", "KATA Marine Malaysia":"Kata Skincare Malaysia", "KATA Singapore":"Kata Skincare Malaysia", "Kata Skincare Singapore":"Kata Skincare Malaysia", "livact.os.sg":"LivAct Official Store", "M Formula SG":"MFormula Official", "MCS Malaysia":"MCS Skincare by CTG4u", "MCS Singapore":"MCS Skincare by CTG4u",
  "NatureLish Healthcare":"NatureLish Recovit by CTG4u", "Naturelish Healthcare Singapore":"NatureLish Recovit by CTG4u", "Ninoko Singapore":"NINOKO Official Store", "NomoQ Malaysia":"NomoQ by CTG4u", "Scale Gem SG":"Scale Gem Collagen by CTG4u", "Scale Story SG":"Scale Story Official Store", "SkinDae Official Store":"SkinDae MY by CTG4u", "SkinDae SG":"SkinDae MY by CTG4u",
  "Uro360 by CTG4u":"Naturelish Uro360 by CTG4u", "Zeero MY":"Zeero Skincare Official", "Zeero SG":"Zeero Skincare Official", "Zeero Skincare SG":"Zeero Skincare Official",
};
export function directoryStoreNameFor(storeName: string): string { return aliases[storeName] ?? storeName; }
export function contactsForStore(storeName: string): ProjectContact[] { return links[directoryStoreNameFor(storeName)] ?? []; }
