alter table public.customer_users add column if not exists display_name text;
alter table public.customer_users add column if not exists active boolean not null default true;
alter table public.customer_users add column if not exists module_access_mode text not null default 'role_default';
alter table public.customer_users add column if not exists store_access_mode text not null default 'all';

alter table public.customer_users drop constraint if exists customer_users_module_access_mode_check;
alter table public.customer_users add constraint customer_users_module_access_mode_check check (module_access_mode in ('role_default','custom'));
alter table public.customer_users drop constraint if exists customer_users_store_access_mode_check;
alter table public.customer_users add constraint customer_users_store_access_mode_check check (store_access_mode in ('all','selected'));

create table if not exists public.user_module_permissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.customer_users(id) on delete cascade,
  module_id text not null,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint user_module_permissions_module_check check (module_id in ('overview','design','calculator','packages','advertising','orders','health','protection','actions')),
  constraint user_module_permissions_user_module_key unique (user_id,module_id)
);
create index if not exists user_module_permissions_user_idx on public.user_module_permissions(user_id);

create table if not exists public.user_store_access (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.customer_users(id) on delete cascade,
  store_id text not null references public.stores(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint user_store_access_user_store_key unique (user_id,store_id)
);
create index if not exists user_store_access_user_idx on public.user_store_access(user_id);

alter table public.user_module_permissions enable row level security;
alter table public.user_store_access enable row level security;
revoke all on table public.user_module_permissions from anon, authenticated;
revoke all on table public.user_store_access from anon, authenticated;
