create table public.co_fund_vouchers (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id),
  store_id text not null references public.stores(id),
  source_store_name text not null,
  campaign_name text not null,
  campaign_date date,
  voucher_name text not null,
  discount_amount_cents bigint not null check (discount_amount_cents >= 0),
  currency text not null default 'MYR' check (currency = 'MYR'),
  quantity integer not null check (quantity >= 0),
  source_sheet_id text,
  source_tab text,
  source_row integer check (source_row is null or source_row > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, store_id, campaign_name, voucher_name, discount_amount_cents),
  unique nulls not distinct (source_sheet_id, source_tab, source_row)
);

create index co_fund_vouchers_campaign_date_idx
  on public.co_fund_vouchers (campaign_date desc);

create index co_fund_vouchers_store_id_idx
  on public.co_fund_vouchers (store_id);

alter table public.co_fund_vouchers enable row level security;

revoke all on table public.co_fund_vouchers from anon, authenticated;
grant select, insert, update, delete on table public.co_fund_vouchers to service_role;
grant usage, select on sequence public.co_fund_vouchers_id_seq to service_role;

insert into public.co_fund_vouchers (
  tenant_id, store_id, source_store_name, campaign_name, campaign_date,
  voucher_name, discount_amount_cents, currency, quantity,
  source_sheet_id, source_tab, source_row
)
values
  ('j-packaging','shopee-agepros-by-swissmed','agepros.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',45,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',2),
  ('j-packaging','shopee-berlanco-beauty-official','berlanco.beauty','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',126,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',3),
  ('j-packaging','shopee-beyoute-official-store','beyoute.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',57,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',4),
  ('j-packaging','shopee-bonlife-official-store','bonlife.os','15 Aug CoFund','2026-08-15','VTH20_50%_15 Aug Cofund DHT',3000,'MYR',38,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',5),
  ('j-packaging','shopee-naturelish-bugucare-by-ctg4u','bugucare.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',32,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',6),
  ('j-packaging','shopee-daionica-official-store','daionica.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',18,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',7),
  ('j-packaging','shopee-goherb-official-store','go_herb','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',190,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',8),
  ('j-packaging','shopee-ilady-haircare-by-ctg4u','ilady.haircare','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',46,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',9),
  ('j-packaging','shopee-jen-mommy-essential-oil','jenmommy.official','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',60,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',10),
  ('j-packaging','shopee-kata-skincare-malaysia','kata_skincare','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',103,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',11),
  ('j-packaging','shopee-livact-official-store','livact.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',60,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',12),
  ('j-packaging','shopee-master-nerv-official-store','masternerv.os','8 Aug CoFund DDV','2026-08-08','Cofund DDV 8 Aug [15%]',3000,'MYR',167,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',13),
  ('j-packaging','shopee-mcs-skincare-by-ctg4u','mcsmalaysia','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',59,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',14),
  ('j-packaging','shopee-mformula-official','mformula_official','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',72,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',15),
  ('j-packaging','shopee-mizino-official-store','mizino.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',57,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',16),
  ('j-packaging','shopee-mizino-premium','mizino.premium','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',189,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',17),
  ('j-packaging','shopee-moesie-malaysia','moesie.my','15 Aug CoFund','2026-08-15','15th Aug - RM20 OFF MS RM200 (D02)',3000,'MYR',5000,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',18),
  ('j-packaging','shopee-m-skinpro-by-ctg4u','mplus.hq','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund MT',3000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',19),
  ('j-packaging','shopee-ninoko-official-store','ninoko_childhood_guardian','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',149,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',20),
  ('j-packaging','shopee-nomoq-by-ctg4u','nomoq.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',62,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',21),
  ('j-packaging','shopee-petavit-official-store','petavit.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',23,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',22),
  ('j-packaging','shopee-scale-gem-collagen-by-ctg4u','scalegem_malaysia','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',14,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',23),
  ('j-packaging','shopee-scale-story-official-store','scalestory.official','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',36,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',24),
  ('j-packaging','shopee-skindae-my-by-ctg4u','skindae.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',139,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',25),
  ('j-packaging','shopee-yuan-chuan-tang-herbal-by-ctg4u','yct.herbal','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',3000,'MYR',32,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',26),
  ('j-packaging','shopee-zeero-skincare-official','zeero_skincare','15 Aug CoFund','2026-08-15','VTH20_50%_15 Aug Cofund DHT',3000,'MYR',48,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',27),
  ('j-packaging','shopee-biotech-by-swissmed','biotech.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',300,'MYR',167,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',28),
  ('j-packaging','shopee-naturelish-isokae-by-ctg4u','isokae_my','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',300,'MYR',167,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',29),
  ('j-packaging','shopee-bonlife-official-store','bonlife.os','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',2200,'MYR',205,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',30),
  ('j-packaging','shopee-zeero-skincare-official','zeero_skincare','15 Aug CoFund','2026-08-15','VTH16_50%_15 Aug Cofund DHT',2200,'MYR',258,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',31),
  ('j-packaging','shopee-ctg4u-malaysia','ctg4u_malaysia','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',32),
  ('j-packaging','shopee-naturelish-eco-plus-by-ctg4u','ecoplus.os','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',33),
  ('j-packaging','shopee-funffy-by-ctg4u','funffy_my','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',34),
  ('j-packaging','shopee-jourish-natural-wellness','jourishwellness','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',35),
  ('j-packaging','shopee-naturelish-recovit-by-ctg4u','naturelish.recovit','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',36),
  ('j-packaging','shopee-true-golden-care-by-naturelish','tgc_my','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',37),
  ('j-packaging','shopee-naturelish-uro360-by-ctg4u','uro360_my','15 Aug CoFund','2026-08-15','15 Aug - RM20 OFF MS RM200',2000,'MYR',100,'1Q2pilQpjJlXDVn8swm44q0yWgTDWE7Dg3Kt-Xk3Cufc','Sheet1',38)
on conflict (source_sheet_id, source_tab, source_row)
do update set
  tenant_id = excluded.tenant_id,
  store_id = excluded.store_id,
  source_store_name = excluded.source_store_name,
  campaign_name = excluded.campaign_name,
  campaign_date = excluded.campaign_date,
  voucher_name = excluded.voucher_name,
  discount_amount_cents = excluded.discount_amount_cents,
  currency = excluded.currency,
  quantity = excluded.quantity,
  updated_at = now();
