alter table public.customer_users
  drop constraint if exists customer_users_role_check;

alter table public.customer_users
  add constraint customer_users_role_check
  check (role in ('customer', 'manager', 'superadmin'));

create table if not exists public.tenant_module_permissions (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  module_id text not null,
  enabled boolean not null default true,
  updated_by text,
  updated_at timestamptz not null default now(),
  constraint tenant_module_permissions_module_check check (module_id in ('overview','design','calculator','packages','advertising','orders','health','protection','actions')),
  constraint tenant_module_permissions_tenant_module_key unique (tenant_id, module_id)
);

create index if not exists tenant_module_permissions_tenant_idx
  on public.tenant_module_permissions(tenant_id);

alter table public.tenant_module_permissions enable row level security;
revoke all on table public.tenant_module_permissions from anon, authenticated;

update public.customer_users
set role = 'superadmin'
where lower(email) = 'shopeehub.ctg@gmail.com';
